### ISSUE TITLE
Create and update logo

### ISSUE THREAD

**Issue by imkrishnasarathi** [imkrishnasarathi/PleasantWeb#13]
Update the current logo of the application and change the file names in the code too

**Comment by johnlundy94** [comment]
Hello @imkrishnasarathi,
Checking in to see if you still needed help with this issue. Would love to work on it.

**Comment by imkrishnasarathi** [comment]
Yes! Continue with your work! But, don't forget to update the logo file location and name in the json

**Comment by johnlundy94** [comment]
Absolutely, I have some ideas. I can return back to this thread tomorrow with a few options for you to choose and then code it in.

**Comment by imkrishnasarathi** [comment]
cool!

**Comment by johnlundy94** [comment]
Awesome got together a bunch of options. Let me know what you think. Also, if you want me to head in a different direction with design let me know. 
![pw1](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/ffc0b63a-c308-45fc-81f8-84e10e506010)
![pw2](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/dfe4bc87-36a9-44bb-9698-9bacf8a99c37)
![pw3](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/83e71b66-974d-472a-bcea-044d28d80132)
![pw4](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/30648de7-4156-43df-9efd-f6e9ff96172c)
![pwsubtext2](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/24943cd7-db93-45dc-b173-7b2c39861634)
![pwsubtext3](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/6e1f296c-afe9-4654-81be-a88213841814)
![pwsubtext4](https://github.com/imkrishnasarathi/PleasantWeb/assets/79663204/5bc30687-3e75-4019-86d2-6e3c88f96278)

**Comment by imkrishnasarathi** [comment]
The second logo looks good! You can continue with that!

**Comment by johnlundy94** [comment]
Awesome, just got it done. Let me know what you think!

**Comment by imkrishnasarathi** [comment]
> Awesome, just got it done. Let me know what you think!

Merged the PR. Thanks for contributing!
