### ISSUE TITLE
Style the extension popup interface

### ISSUE THREAD

**Issue by imkrishnasarathi** [imkrishnasarathi/PleasantWeb#14]
The design of the extension interface including the table can be styled. If you can, go ahead and do this!

**Comment by TumiMoshou** [comment]
Hi, I am looking to contribute to my first open source project and wanted to know if I could please work on this issue?

**Comment by imkrishnasarathi** [comment]
@TumiMoshou Go Ahead! All contributions are welcome

**Comment by TumiMoshou** [comment]
Hi @imkrishnasarathi, I am trying to push my changes but I get the following message: 'Permission to imkrishnasarathi/PleasantWeb.git denied to TumiMoshou.'

**Comment by imkrishnasarathi** [comment]
Hey there. I am sorry for the issue. Can you please inform if it is okay now?

**Comment by TumiMoshou** [comment]
Hey, yes it is fine now and seems to be working. Thank you
