### ISSUE TITLE
Style the extension options interface

### ISSUE THREAD

**Issue by imkrishnasarathi** [imkrishnasarathi/PleasantWeb#15]
Style the extension options interface. If you want to open the extension options, follow these steps:
1. Go to Manage Extensions 
2. Click on the "Details" button below the extension
3. Scroll down and click on the "Extension Options" button.

Go ahead and do it your way!

**Comment by enjiruuuu** [comment]
hi @imkrishnasarathi  , i'm looking to make a contribution. may i please work on this issue? :)

**Comment by imkrishnasarathi** [comment]
go ahead @enjiruuuu !

**Comment by enjiruuuu** [comment]
@imkrishnasarathi thank you! i've made changes in the linked PR, please take a look 😄
