### ISSUE TITLE
API Key to be hidden

### ISSUE THREAD

**Issue by imkrishnasarathi** [imkrishnasarathi/PleasantWeb#3]
The API key is to be hidden so that people on github cannot see it. even people who download the unpacked extension should not be able to see it. Currently it is being revealed to everyone. Solutions?

**Comment by Vaishali785** [comment]
> The API key is to be hidden so that people on github cannot see it. even people who download the unpacked extension should not be able to see it. Currently it is being revealed to everyone. Solutions?

Is it a react project? If not, which framework/library are you using for this project?

**Comment by imkrishnasarathi** [comment]
no frameworks. vanilla js

**Comment by Shikhar02347893** [comment]
hi @imkrishnasarathi , can you please assign me the issue.

**Comment by imkrishnasarathi** [comment]
@Vaishali785 are you doing this? Or I'm assigning this to Shikhar

**Comment by imkrishnasarathi** [comment]
I'll wait sometime for your reply. If @Vaishali785 does not do this, I'll assign it to you @Shikhar02347893. You can go ahead and work on this and submit the PR. If it works, I'll accept it

**Comment by Shikhar02347893** [comment]
okay @imkrishnasarathi

**Comment by Vaishali785** [comment]
> I'll wait sometime for your reply. If @Vaishali785 does not do this, I'll assign it to you @Shikhar02347893. You can go ahead and work on this and submit the PR. If it works, I'll accept it

You can assign it to @Shikhar02347893 , as I'm working on something else right now.

**Comment by imkrishnasarathi** [comment]
Okay. @Shikhar02347893 you can work on this

**Comment by virajp4** [comment]
hey @imkrishnasarathi can i work on this?

**Comment by imkrishnasarathi** [comment]
@virajp4 A person is already working, but go ahead. Who knows if you have a different solution. Happy Coding :)

**Comment by Shikhar02347893** [comment]
@imkrishnasarathi i am working on the issue... but you have not officially assigned me the issue

**Comment by imkrishnasarathi** [comment]
done

**Comment by sora-san45** [comment]
can you assign this issue to me please

**Comment by imkrishnasarathi** [comment]
go ahead. I have a solution, we have to follow that else it is difficult to achieve what we are trying. what you have to do is:
Create a config.json file where you read it from and add it to the gitignore. The content.js should read the two apis from there and use which one is required based on the situation from the two api keys

**Comment by ich-tanishqa** [comment]
please assign this task to me
@imkrishnasarathi
