### ISSUE TITLE
Readme file not present

### ISSUE THREAD

**Issue by Veerhan-glitch** [imkrishnasarathi/PleasantWeb#4]
Hey, want me to create one for you?

See my [ALG](https://github.com/Veerhan-glitch/Alg) for an overview of my style of README

**Comment by imkrishnasarathi** [comment]
Yeah why not! that's a real problem. Just overview the code, and create a basic README. We can improve later

**Comment by virajp4** [comment]
hey, can i work on this?

**Comment by imkrishnasarathi** [comment]
@virajp4 Already done. You can improve the new README
