### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by ayushmankoley** [imkrishnasarathi/PleasantWeb#5]
Hey Im interested

**Comment by imkrishnasarathi** [comment]
Another person already got into this, but go ahead :) . Then I'll see what to do. You can go ahead, and edit the readme then submit a PR

**Comment by ayushmankoley** [comment]
Hey do assign the pr to this and close this thankyou

**Comment by ayushmankoley** [comment]
Completed by https://github.com/imkrishnasarathi/PleasantWeb/pull/7
